### ISSUE TITLE
Missing server-side rendering support

### ISSUE THREAD

**Issue by berbaquero** [berbaquero/react-hide-show-utils#1]
Since this uses the browser's `matchMedia` API, it currently can't work on the server.

One fix idea is to **always** render the children in the server, and after detecting the active breakpoint, mount or un-mount accordingly on the client, on `componentDidMount`.

Another option is to **never** render any children in the server, and only do it if the breakpoint is active on the browser - also on `componentDidMount`.

**Comment by berbaquero** [comment]
If we choose to render the children on the server, we can always hide them by default with inline styles initially, so at least they are not visible on initial page-view, but they are still part of the DOM.

**Comment by supra28** [comment]
Would be great to get some insight from AirBnb :P

**Comment by sbolel** [comment]
🤔 I wonder if React 16 will make this a bit easier. 

> One fix idea is to always render the children in the server, and after detecting the active breakpoint, mount or un-mount accordingly on the client, on `componentDidMount`.

This approach makes sense to me. I wonder if React 16's [Portals](https://reactjs.org/docs/portals.html) may be of help here?

**Comment by berbaquero** [comment]
Still not super familiar with Portals myself. Will look into. I already did some work on this as well but didn't have to finish it. Will see if I push it to a WIP branch!

**Comment by berbaquero** [comment]
I gave it a shot with #4!

(Same PR could help you @sbolel, if you want to follow-up on #2 🙂)

**Comment by sbolel** [comment]
Oh awesome!

**Comment by sbolel** [comment]
Just looked through #4, looks great dude -- reviewed! Definitely gives me a great start for #2. Thanks!!
