### ISSUE TITLE
Missing tests

### ISSUE THREAD

**Issue by berbaquero** [berbaquero/react-hide-show-utils#2]

**Comment by sbolel** [comment]
How do you feel about using Jest+Enzyme? If those work, I can get testing started -- at the least I'll setup the test suite and get a test running.

**Comment by berbaquero** [comment]
Yes, Jest and Enzyme would be my choice as well!

**Comment by sbolel** [comment]
Awesome, I'll get it started this weekend.

**Comment by sbolel** [comment]
Sorry, totally forgot :(

**Comment by berbaquero** [comment]
@sbolel hey, don't be sorry! — there's no need :)

Thanks for taking interest anyway :)
